### PR TITLE
check number of readings in 300 row

### PR DESCRIPTION
**Pull request by matt-telstra**
I've received a nem12 file from a meter data provider which has a 200 row specifying 15 minute intervals, then 300 and 400 rows for 288 intervals (i.e. 5 minutes). So the file is invalid.

The code today will not detect this issue for a 300 row. (But will for a 400 row, but only if the error is in one direction not the other).

The impact was that 2/3 of the readings were dropped, and the remaining readings didn't have the correct timestamps assigned. This would also impact all the stuff parsed at the end of the line. Instead of datetimes and reasons, the readings would end up in those fields.

I'm just crafting this PR in a hurry, because it's Friday afternoon and I'm about to log off. I just want to start the discussion, even if this PR isn't ready to merge.

I have not yet added a unit test for this. So test coverage will probably decrease. Would you like me to add a test for this?

I am wondering why pydantic did not notice that floats are ending up in the `msats_load_datetime` field. Surely it should have noticed that was wrong? (This is why I was a bit hesitant to remove pydantic in my other PR.) Perhaps it's because the 400 row failed to be parsed, prior to pydantic validating the 300 row after all rows were passed. We should check with a NEM12 that has a 200 row for 15 minutes, a 300 row for 5 minutes, and then *no* 400 row.

I know I've been asking for this library to be faster. This change slows us down from 30 seconds to 31 seconds, for that particular sample file you crafted. But I think the increased robustness is worth it.

### CODE REVIEW

**Comment by matt-telstra** [comment]
Also, I should probably change that magic `7` to something else.

Perhaps a copy-paste of the schema for each row into the comments for each `parse_xxx_row` function would make it easier to understand the code?

**Comment by mdavis-xyz** [comment]
@aguinane what do you think about this?

Do I need to add unit tests for this? Should I move the magic numbers into variables?

**Comment by matt-telstra** [comment]
@aguinane what do you think about this?

Do I need to add unit tests for this? Should I move the magic numbers into variables?

**Comment by aguinane** [comment]
Ideally an example file to unit test would be helpful.
is the intent to self-correct or just throw an error? Note there is also a strict variable for this purpose if the intention is to automatically fix itself. 
is the 7 just the number of non-interval values? probably worth adding a comment at least explaining why it's 7 but happy for it to be hardcoded since presumably this will be fixed.

**Comment by mdavis-xyz** [comment]
For my use case I just want an exception thrown. I think attempting to correct would be difficult, and perhaps not possible in general.

Yes I can try to add a unit test.
Where/how?
Should I add a new .py file in the tests folder? And a new nem12 file in examples/invalid/ ?

Yep, that's what 7 is. I can add a comment, or define it.

**Comment by matt-telstra** [comment]
For my use case I just want an exception thrown. I think attempting to correct would be difficult, and perhaps not possible in general.

Yes I can try to add a unit test.
Where/how?
Should I add a new .py file in the tests folder? And a new nem12 file in examples/invalid/ ?

Yep, that's what 7 is. I can add a comment, or define it.

**Comment by matt-telstra** [comment]
I've pushed some changes with unit tests.

Note that the standard says that 400 rows must add up to a whole day.

If the 200 row says we have 30 minute data, and the last 400 row has an EndInterval of 24*60/15 not 24*60/30, we know something is wrong. But if the 200 row says we have 15 minute data, and the 400 row only goes up to 24*60/30, not 24*60/15, then that's an invalid file. But we currently don't catch that. (My new unit test fails.) That's because you can't validate that on a per-row basis. You have to do something in `parse_nem12_rows` to say "was that the last 400 for a while? If so do an additional check". Similarly, if the 400 rows are not consecutive and chronological, we won't notice.

So are those kinds of validity checks just out of scope for now? Or is there an easy way to add them?

**Comment by matt-telstra** [comment]
Have you had a chance to look at my latest commit for this?

Should I just disable the failing test since it's hard to detect that error?

**Comment by matt-telstra** [comment]
I've just noticed that this change broke existing tests. I mistakenly thought 300 rows are indexed from 0, not 1. I've changed that now.

And I've skipped the test that doesn't pass without rearchitecting the parser. I used `@pytest.mark.skip()`. Let me know if you'd rather I delete it or comment it out.

**Pull request merged**
