### PR TITLE
Improve performance

### LINKED ISSUE #35: Improve performance
I'm deploying this library to AWS Lambda functions, which have a maximum runtime of 15 minutes.
For 14MB files I'm getting timeouts. 

I'm not here to complain though. I want to write a PR to improve this library to make it faster.
I'm raising this ticket so we can start the discussion to identify where the bottleneck is, and so I can come up with a plan to improve it.

Do you know off the top of your head where the bottleneck is?

I suspect it's the list comprehension that instantiates one named tuple per row, [here](https://github.com/aguinane/nem-reader/blob/16eba1b459e0d3cd9765e795572e0012386a1cbe/nemreader/nem_reader.py#L367). Does that sound like it's the bottleneck?

I'm still not super familiar with the code, or even the nem12 format. 

`parse_reading(val)` sounds pretty trivial. If that's the bottleneck we can probably find a way to do that casting with numpy.

Is it the fact that this is a list or named tuples, instead of a pandas dataframe from the start? Pandas can parse CSVs pretty quickly, and you can tell it to ignore the first M rows and last N rows. My use case is only to output as a pandas dataframe (to dump to parquet). Would it be acceptable if every use involved casting the data to a pandas dataframe (and then possibly back to an Iterable of named tuples or whatever, to avoid making it a breaking change.)

Is it a big deal if we have to do two passes of the file? 
 (e.g. for certain streamable file-like objects, they're not seekable, so we'd have to cache it in memory.)

### PR DESCRIPTION
**Pull request by matt-telstra**
Somewhat fixes #35 .

The main change here is to factor out the dictionary of readings into a `pydantic.BaseModel`. This means we don't re-validate it as we pass it around into multiple parent classes. I had to write some repetative methods that just expose the methods of `__root__`.

The downsize of this approach is that the `readings` attribute is no longer a literal dictionary, even though it should still be usable with the same methods as a dictionary. I don't know if that's a backwards incompatable change?

The `copy_on_model_validation` was a slight speedup. This skips copying of the data, but validation is still done.

### CODE REVIEW

**Comment by aguinane** [comment]
Is it faster still to remove the pydantic checks completely? (I'm happy for you to do this as long as all the tests still pass.

**Comment by matt-telstra** [comment]
Yes. The speed improvement is doubled if we drop pydantic from those top two classes.

With the sample data from before, `master` takes 34 seconds. This pull request takes around 21 seconds. With no pydantic for those top two classes it drops to 6 seconds.

The `pytest` tests still pass without pydantic for that top class.

The downside is that we lose validation of the underlying data. (e.g. datetime vs str).
Have you ever seen pydantic's validation catch an invalid NEM12 file? 
Are there any implicit coercions (e.g. casting string to datetime) which we would lose? (The tests pass, but I don't know how comprehensive they are.)

**Comment by matt-telstra** [comment]
I've just pushed a commit to remove pydantic, so you can see.

**Comment by matt-telstra** [comment]
The CICD checks failed. It looks like a CICD config issue, but I'm not sure.

**Comment by aguinane** [comment]
Yep the tests passed just the coveralls stuff failed (maybe because its a PR..).

**Pull request merged**
